In [1]:
import pandas as pd
import numpy as np

In [2]:
import sys
print(sys.version)

3.11.13 (main, Jun  3 2025, 18:38:25) [Clang 17.0.0 (clang-1700.0.13.3)]

In [3]:
df = pd.read_csv("augmented data.csv")

In [4]:
df.drop("Timestamp", axis=1, inplace=True)
df.drop(
    'Without using AI, write a paragraph :\n"If the internet disappeared tomorrow, how would your life change?"\nPlease write without AI assistance. This helps us measure natural creativity and mental effort.',
    axis=1,
    inplace=True
)

In [5]:
df

,Age,Gender,Educational Background,"Do you regularly use AI tools (e.g., ChatGPT, Grammarly)","If yes, how often?",What tasks do you use AI for?,"On a scale of 1–5, how dependent do you feel on AI?",Were you aware that AI could generate write-ups?,How mentally tiring was the task?,How confident are you in your originality?,Were you tempted to use AI while writing?,Do you feel AI has reduced your own creativity?
0,18,Female,Undergraduate,Yes,Multiple times a day,Writing;Research,3,yes,9.0,8.0,No,Yes
1,44,Female,Postgraduate / PhD,Yes,Once a day,Writing;Research;Brainstorming,2,yes,2.0,10.0,No,No
2,19,Male,Undergraduate,Yes,Once a day,Research,3,yes,3.0,8.0,No,Yes
3,21,Male,Undergraduate,Yes,Rarely,Writing;Research;Brainstorming,2,No,5.0,8.0,Yes,Yes
4,22,Male,Graduate,Yes,Rarely,Research,4,yes,5.0,3.0,Yes,Maybe
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,22,Male,Graduate,Yes,Multiple times a day,Writing;Research,3,yes,3.0,7.0,Yes,Yes
4996,23,Male,Graduate,Yes,Multiple times a day,Research,4,yes,6.0,10.0,Yes,Yes
4997,21,Female,Graduate,No,NaN,NaN,1,yes,1.0,10.0,No,Yes
4998,20,Male,Undergraduate,Yes,Multiple times a day,Writing;Research;Coding,4,yes,6.0,4.0,Yes,Yes
4999,22,Female,Graduate,Yes,Once a day,Writing;Research;Brainstorming,3,No,1.0,10.0,No,Yes

In [6]:
df.head()

,Age,Gender,Educational Background,"Do you regularly use AI tools (e.g., ChatGPT, Grammarly)","If yes, how often?",What tasks do you use AI for?,"On a scale of 1–5, how dependent do you feel on AI?",Were you aware that AI could generate write-ups?,How mentally tiring was the task?,How confident are you in your originality?,Were you tempted to use AI while writing?,Do you feel AI has reduced your own creativity?
0,18,Female,Undergraduate,Yes,Multiple times a day,Writing;Research,3,yes,9.0,8.0,No,Yes
1,44,Female,Postgraduate / PhD,Yes,Once a day,Writing;Research;Brainstorming,2,yes,2.0,10.0,No,No
2,19,Male,Undergraduate,Yes,Once a day,Research,3,yes,3.0,8.0,No,Yes
3,21,Male,Undergraduate,Yes,Rarely,Writing;Research;Brainstorming,2,No,5.0,8.0,Yes,Yes
4,22,Male,Graduate,Yes,Rarely,Research,4,yes,5.0,3.0,Yes,Maybe

In [7]:
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer

for col in df.select_dtypes(include='object').columns:
    df[col] = LabelEncoder().fit_transform(df[col].astype(str))
    
imputer = SimpleImputer(strategy='most_frequent')
df = pd.DataFrame(imputer.fit_transform(df), columns=df.columns)

print(df.head())

   Age   Gender  Educational Background  \
0   5.0     0.0                     3.0
1  32.0     0.0                     2.0
2   6.0     1.0                     3.0
3   9.0     1.0                     3.0
4  10.0     1.0                     0.0

   Do you regularly use AI tools (e.g., ChatGPT, Grammarly)  \
0                                                1.0
1                                                1.0
2                                                1.0
3                                                1.0
4                                                1.0

   If yes, how often?  What tasks do you use AI for?   \
0                 1.0                            20.0
1                 2.0                            21.0
2                 2.0                             7.0
3                 3.0                            21.0
4                 3.0                             7.0

   On a scale of 1–5, how dependent do you feel on AI?  \
0                                                3.0
1                                                2.0
2                                                3.0
3                                                2.0
4                                                4.0

   Were you aware that AI could generate write-ups?  \
0                                               1.0
1                                               1.0
2                                               1.0
3                                               0.0
4                                               1.0

   How mentally tiring was the task?  \
0                                9.0
1                                2.0
2                                3.0
3                                5.0
4                                5.0

   How confident are you in your originality?  \
0                                         8.0
1                                        10.0
2                                         8.0
3                                         8.0
4                                         3.0

   Were you tempted to use AI while writing?  \
0                                        0.0
1                                        0.0
2                                        0.0
3                                        1.0
4                                        1.0

   Do you feel AI has reduced your own creativity?
0                                              2.0
1                                              1.0
2                                              2.0
3                                              2.0
4                                              0.0

/var/folders/c0/fkwzzmb92yldm18l2b0gx5wh0000gn/T/ipykernel_2669/1531771419.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include='object').columns:

In [8]:
target_column = "Do you feel AI has reduced your own creativity?"
X = df.drop(target_column, axis=1).astype(np.float64)
y = df[target_column].astype(int)

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [10]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

tree = DecisionTreeClassifier(random_state=42)

tree.fit(X_train, y_train)

pred = tree.predict(X_test)
acc = accuracy_score(y_test, pred)

print("Decision tree Accuracy", acc)

Decision tree Accuracy 0.368

In [11]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

acc = accuracy_score(y_test, pred)

print("Random Forest Accuracy:", acc)

Random Forest Accuracy: 0.438