In [1]:
import sys

print(sys.executable)

/opt/homebrew/opt/python@3.11/bin/python3.11

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("Study on AI Dependency and Cognitive Creativity.csv")
df.drop("Timestamp", axis=1,inplace=True)
df.drop(
    'Without using AI, write a paragraph :\n"If the internet disappeared tomorrow, how would your life change?"\nPlease write without AI assistance. This helps us measure natural creativity and mental effort.',
    axis=1,
    inplace=True
)

In [4]:
df

,Age,Gender,Educational Background,"Do you regularly use AI tools (e.g., ChatGPT, Grammarly)","If yes, how often?",What tasks do you use AI for?,"On a scale of 1–5, how dependent do you feel on AI?",Were you aware that AI could generate write-ups?,How mentally tiring was the task?,How confident are you in your originality?,Were you tempted to use AI while writing?,Do you feel AI has reduced your own creativity?
0,47,Male,Postgraduate / PhD,Yes,Multiple times a day,Writing;Research;Coding;Brainstorming,4,NaN,3.0,NaN,No,Maybe
1,19,Male,Undergraduate,Yes,Multiple times a day,Research;Coding;Brainstorming,3,NaN,1.0,10.0,Yes,yes
2,19,Female,Graduate,Yes,Once a day,Writing;Research;Coding,3,yes,6.0,9.0,Yes,yes
3,14,Female,High school or below,Yes,Once a day,Writing;Coding,2,yes,8.0,10.0,No,yes
4,20,Male,Graduate,Yes,Multiple times a day,Writing;Research;Coding;Brainstorming,3,yes,4.0,8.0,No,yes
...,...,...,...,...,...,...,...,...,...,...,...,...
95,22,Male,Undergraduate,Yes,Multiple times a day,Research,4,yes,6.0,6.0,No,Maybe
96,20,Male,Undergraduate,Yes,Multiple times a day,Writing;Research;Coding;Brainstorming;Academic...,2,yes,1.0,8.0,No,Maybe
97,22,Female,Graduate,Yes,Once a day,Writing;Academic Work,2,yes,2.0,5.0,No,Yes
98,23,Female,Postgraduate / PhD,Yes,Multiple times a day,Writing;Research;Coding;Academic Work,3,yes,4.0,9.0,Yes,Yes
99,22,Female,Postgraduate / PhD,Yes,Multiple times a day,Coding;Brainstorming;Academic Work,3,yes,1.0,10.0,No,No

In [5]:
df.head()

,Age,Gender,Educational Background,"Do you regularly use AI tools (e.g., ChatGPT, Grammarly)","If yes, how often?",What tasks do you use AI for?,"On a scale of 1–5, how dependent do you feel on AI?",Were you aware that AI could generate write-ups?,How mentally tiring was the task?,How confident are you in your originality?,Were you tempted to use AI while writing?,Do you feel AI has reduced your own creativity?
0,47,Male,Postgraduate / PhD,Yes,Multiple times a day,Writing;Research;Coding;Brainstorming,4,NaN,3.0,NaN,No,Maybe
1,19,Male,Undergraduate,Yes,Multiple times a day,Research;Coding;Brainstorming,3,NaN,1.0,10.0,Yes,yes
2,19,Female,Graduate,Yes,Once a day,Writing;Research;Coding,3,yes,6.0,9.0,Yes,yes
3,14,Female,High school or below,Yes,Once a day,Writing;Coding,2,yes,8.0,10.0,No,yes
4,20,Male,Graduate,Yes,Multiple times a day,Writing;Research;Coding;Brainstorming,3,yes,4.0,8.0,No,yes

In [6]:
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer

for col in df.select_dtypes(include='object').columns:
    df[col] = LabelEncoder().fit_transform(df[col].astype(str))
    
imputer = SimpleImputer(strategy='most_frequent')
df = pd.DataFrame(imputer.fit_transform(df), columns=df.columns)

print(df.head())

   Age   Gender  Educational Background  \
0  21.0     1.0                     2.0
1   3.0     1.0                     3.0
2   3.0     0.0                     0.0
3   1.0     0.0                     1.0
4   5.0     1.0                     0.0

   Do you regularly use AI tools (e.g., ChatGPT, Grammarly)  \
0                                                1.0
1                                                1.0
2                                                1.0
3                                                1.0
4                                                1.0

   If yes, how often?  What tasks do you use AI for?   \
0                 1.0                            27.0
1                 1.0                             9.0
2                 2.0                            25.0
3                 2.0                            16.0
4                 1.0                            27.0

   On a scale of 1–5, how dependent do you feel on AI?  \
0                                                4.0
1                                                3.0
2                                                3.0
3                                                2.0
4                                                3.0

   Were you aware that AI could generate write-ups?  \
0                                               3.0
1                                               3.0
2                                               1.0
3                                               1.0
4                                               1.0

   How mentally tiring was the task?  \
0                                3.0
1                                1.0
2                                6.0
3                                8.0
4                                4.0

   How confident are you in your originality?  \
0                                        10.0
1                                        10.0
2                                         9.0
3                                        10.0
4                                         8.0

   Were you tempted to use AI while writing?  \
0                                        0.0
1                                        1.0
2                                        1.0
3                                        0.0
4                                        0.0

   Do you feel AI has reduced your own creativity?
0                                              0.0
1                                              5.0
2                                              5.0
3                                              5.0
4                                              5.0

/var/folders/c0/fkwzzmb92yldm18l2b0gx5wh0000gn/T/ipykernel_2747/1531771419.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include='object').columns:

In [7]:
target_column = "Do you feel AI has reduced your own creativity?"
X = df.drop(target_column, axis=1).astype(np.float64)
y = df[target_column].astype(int)

In [8]:
X

,Age,Gender,Educational Background,"Do you regularly use AI tools (e.g., ChatGPT, Grammarly)","If yes, how often?",What tasks do you use AI for?,"On a scale of 1–5, how dependent do you feel on AI?",Were you aware that AI could generate write-ups?,How mentally tiring was the task?,How confident are you in your originality?,Were you tempted to use AI while writing?
0,21.0,1.0,2.0,1.0,1.0,27.0,4.0,3.0,3.0,10.0,0.0
1,3.0,1.0,3.0,1.0,1.0,9.0,3.0,3.0,1.0,10.0,1.0
2,3.0,0.0,0.0,1.0,2.0,25.0,3.0,1.0,6.0,9.0,1.0
3,1.0,0.0,1.0,1.0,2.0,16.0,2.0,1.0,8.0,10.0,0.0
4,5.0,1.0,0.0,1.0,1.0,27.0,3.0,1.0,4.0,8.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
95,7.0,1.0,3.0,1.0,1.0,7.0,4.0,1.0,6.0,6.0,0.0
96,5.0,1.0,3.0,1.0,1.0,28.0,2.0,1.0,1.0,8.0,0.0
97,7.0,0.0,0.0,1.0,2.0,13.0,2.0,1.0,2.0,5.0,0.0
98,8.0,0.0,2.0,1.0,1.0,26.0,3.0,1.0,4.0,9.0,1.0
99,7.0,0.0,2.0,1.0,1.0,4.0,3.0,1.0,1.0,10.0,0.0

In [9]:
y

0     0
1     5
2     5
3     5
4     5
     ..
95    0
96    0
97    2
98    2
99    1
Name: Do you feel AI has reduced your own creativity?, Length: 100, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [12]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

tree = DecisionTreeClassifier(random_state=42)

tree.fit(X_train, y_train)

pred = tree.predict(X_test)
acc = accuracy_score(y_test, pred)

print("Decision tree Accuracy", acc)

Decision tree Accuracy 0.25

In [13]:
""" now 
its time for random forest
"""

' now \nits time for random forest\n'

In [14]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

acc = accuracy_score(y_test, pred)

print("Random Forest Accuracy:", acc)

Random Forest Accuracy: 0.35

In [15]:
needed_colmns = ["Age","Gender","Educational Background","If yes, how often?","On a scale of 1–5, how dependent do you feel on AI?","Were you aware that AI could generate write-ups?","Were you tempted to use AI while writing?","Do you feel AI has reduced your own creativity?"]